//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azimuth.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azimuth.Migrations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [dbb3b51a6bd6c542a4bacaa3840159ce32]
        ///GO
        ///CREATE TABLE [dbo].[Albums](
        ///	[AlbumId] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[Name] [nvarchar](50) NOT NULL,
        ///	[Description] [nvarchar](500) NULL,
        ///	[ArtistId] [bigint] NOT NULL,
        /// CONSTRAINT [PK_Albums] PRIMARY KEY CLUSTERED 
        ///(
        ///	[AlbumId] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ////****** Object:  Table [dbo].[Artists]    Script Date: 09.08.20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateReleaseSqlServerContent {
            get {
                return ResourceManager.GetString("CreateReleaseSqlServerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Azimuth]
        ///GO
        ///CREATE TABLE [dbo].[Albums](
        ///	[AlbumId] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[Name] [nvarchar](50) NOT NULL,
        ///	[Description] [nvarchar](500) NULL,
        ///	[ArtistId] [bigint] NOT NULL,
        /// CONSTRAINT [PK_Albums] PRIMARY KEY CLUSTERED 
        ///(
        ///	[AlbumId] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ////****** Object:  Table [dbo].[Artists]    Script Date: 09.08.2014 18:37:30 ******/
        ///SET AN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSqlServerContent {
            get {
                return ResourceManager.GetString("CreateSqlServerContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////****** Object:  Table [dbo].[PlaylistTracks]    Script Date: 09.08.2014 18:48:43 ******/
        ///DROP TABLE [dbo].[PlaylistTracks]
        ///GO
        ///
        ////****** Object:  Table [dbo].[Tracks]    Script Date: 09.08.2014 18:48:57 ******/
        ///DROP TABLE [dbo].[Tracks]
        ///GO
        ///
        ////****** Object:  Table [dbo].[Genres]    Script Date: 09.08.2014 18:48:20 ******/
        ///DROP TABLE [dbo].[Genres]
        ///GO
        ///
        ////****** Object:  Table [dbo].[Albums]    Script Date: 09.08.2014 18:49:22 ******/
        ///DROP TABLE [dbo].[Albums]
        ///GO
        ///
        ////****** Object:  Table [dbo].[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DropSqlServerContent {
            get {
                return ResourceManager.GetString("DropSqlServerContent", resourceCulture);
            }
        }
    }
}
